platform:
    - x64

# Workaround for esy/esy#388
environment:
    HOME: C:\Users\appveyor

cache:
    - C:\Users\appveyor\.esy

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g esy@0.2.9
    - cp cygwin1-patched.dll C:/Users/appveyor/AppData/Roaming/npm/node_modules/esy/node_modules/esy-bash/.cygwin/bin/cygwin1.dll
    # Retry is necessary due to esy/esy#413 and esy/esy#414
    - appveyor-retry esy install

build_script:
    - esy build

test: off
